package org.client.app;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

public class AppPanel extends JPanel {
    private ClientApp clientApp;
    private JPanel mainPanel;
    private JScrollPane contactsScrollPane;
    private JLabel errLabel;
    private JPanel messagePanel;
    private JPanel contactsPanel;

    public AppPanel(ClientApp clientApp) {
        this.clientApp = clientApp;

        contactsPanel = new JPanel();
        contactsPanel.setLayout(new BoxLayout(contactsPanel, BoxLayout.Y_AXIS));

        $$$setupUI$$$();
        add(mainPanel);
    }

    public void loadContacts() {
        contactsScrollPane.setViewportView(contactsPanel);
        contactsPanel.removeAll();

        String[] contacts;
        try {
            contacts = clientApp.getClient().getChats();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        for (String contact : contacts) {
            JButton button = new JButton(contact);

            button.addActionListener(e -> {
                ((ChatPanel) messagePanel).loadMessages(contact);
            });

            contactsPanel.add(button);
        }
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        messagePanel = new ChatPanel(clientApp);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, BorderLayout.CENTER);
        contactsScrollPane = new JScrollPane();
        panel1.add(contactsScrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 400), null, 0, false));
        panel1.add(messagePanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 400), new Dimension(-1, 400), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        mainPanel.add(label1, BorderLayout.NORTH);
        errLabel = new JLabel();
        errLabel.setText("Label");
        mainPanel.add(errLabel, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
