package org.client.app;

import org.client.Client;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

public class ClientApp extends JFrame {
    private Client client;
    private JPanel mainPanel;
    private JPanel serverConnectPanel;
    private JPanel loginPanel;
    private JPanel signUpPanel;
    private JPanel appPanel;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        serverConnectPanel = new ServerConnectPanel(this);
        loginPanel = new LoginPanel(this);
        signUpPanel = new SignUpPanel(this);
        appPanel = new AppPanel(this);
    }

    public static void main(String[] args) {
        ClientApp clientApp = new ClientApp();
        clientApp.add(clientApp.mainPanel);
        clientApp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        clientApp.setSize(500, 500);
        clientApp.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new CardLayout(0, 0));
        mainPanel.add(serverConnectPanel, "serverConnectPanel");
        mainPanel.add(loginPanel, "loginPanel");
        mainPanel.add(signUpPanel, "signUpPanel");
        mainPanel.add(appPanel, "appPanel");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public void setCard(String card) {
        if (card.equals("appPanel")) {
            ((AppPanel) appPanel).loadContacts();
        }
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, card);
    }

    public void nextCard() {
        ((CardLayout) mainPanel.getLayout()).next(mainPanel);
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }
}
