package org.client.app;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ContactsPanel extends JPanel {
    private final ClientApp clientApp;
    private final AppPanel appPanel;
    private JPanel mainPanel;
    private JPanel contactsHoldPanel;
    private JLabel contactsLabel;
    private JButton addContactBut;

    public ContactsPanel(ClientApp clientApp, AppPanel appPanel) {
        this.clientApp = clientApp;
        this.appPanel = appPanel;

        add(mainPanel);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        contactsHoldPanel = new JPanel();
        contactsHoldPanel.setLayout(new BoxLayout(contactsHoldPanel, BoxLayout.Y_AXIS));


    }

    public void addContact(String name) {
        JButton button = new JButton(name);

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                appPanel.showChat(name);
            }
        });
    }

    public void resetContacts() {
        contactsHoldPanel.removeAll();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-65536)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        contactsLabel = new JLabel();
        contactsLabel.setHorizontalAlignment(0);
        contactsLabel.setHorizontalTextPosition(0);
        contactsLabel.setText("Contacts");
        mainPanel.add(contactsLabel, BorderLayout.NORTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        addContactBut = new JButton();
        addContactBut.setText("add contact");
        mainPanel.add(addContactBut, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
